<?php return array(
"tury-i-vizy/vizy/" => "catalog/index",
"tury-i-vizy/vizy/search" => "catalog/search",
"tury-i-vizy/vizy/<url:([0-9a-z\/_-]+)>/" => "catalog/tree",
"o-kompanii/sobytiya/" => "news/list",
"o-kompanii/sobytiya/<name:([\w-]+)>/" => "news/item",
"o-kompanii/novosti/" => "news/list",
"o-kompanii/novosti/<name:([\w-]+)>/" => "news/item",
"informaciya/akcii/" => "news/list",
"informaciya/akcii/<name:([\w-]+)>/" => "news/item",
"srochno-gorit/goryaschie-tury/" => "catalog/index",
"srochno-gorit/goryaschie-tury/search" => "catalog/search",
"srochno-gorit/goryaschie-tury/<url:([0-9a-z\/_-]+)>/" => "catalog/tree",
"strany-i-oteli/" => "catalog/index",
"strany-i-oteli/search" => "catalog/search",
"strany-i-oteli/<url:([0-9a-z\/_-]+)>/" => "catalog/tree",
"" => "site/index",
"kontakty" => "site/contacts",
"userlogin" => "client/loginUser",
"search" => "site/search",
"<_c:(profile|user|client)>" => "<_c>/index",
"<_c:(profile|user|client)>/<_a>" => "<_c>/<_a>",
"<_a:(login|logout|register)>" => "user/<_a>",
"<_c>/<_a:(captcha)>/refresh" => "<_c>/<_a>",
"<_c>/<_a:(captcha)>/<v>" => "<_c>/<_a>",
"<url:([0-9a-z\/_-]+)>/" => "site/page",
);
?>